# Generated by Django 5.2.5 on 2025-09-06 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('data', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_system.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_system.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Понеділок'), ('Tue', 'Вівторок'), ('Web', 'Середа'), ('Thu', 'Четверг'), ('Fri', 'Пятниця')], max_length=10)),
                ('start_lessons', models.TimeField()),
                ('end_lessons', models.TimeField()),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_system.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_system.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_system.teacher')),
            ],
        ),
    ]
